### ISSUE TITLE
Missing or misplaced "old" config folder?

### ISSUE THREAD

**Issue by francoisgermain** [state-spaces/s4#130]
Hopefully this is an easy one, but I've looked through the entire repository history and this one has eluded me:
Does the `old/` repository listed in the README indeed exist? And if so, where is it? It doesn't appear to be in this folder unlike what the README seems to indicate (if I'm not missing something): 

https://github.com/state-spaces/s4/blob/a246043077dbff8563a6b172426443dced9a9d96/configs/experiment/README.md?plain=1#L8

I had hoped to run the original S4 experiment on Speech Commands, which would be in this elusive folder according to:
https://github.com/state-spaces/s4/blob/a246043077dbff8563a6b172426443dced9a9d96/models/s4/experiments.md?plain=1#L67

So far, no luck finding this experiment configuration anywhere though :-(

Thanks for the help!

**Comment by albertfgu** [comment]
Don't remember what happened to that folder, but the whole point of deprecating it is that no one should have to use it anymore! (Maybe it was actually just from the internal repo and never meant to be released?)

**Comment by francoisgermain** [comment]
I see. Well, as far as I can tell, it was indeed never released in the github repo (as far as my git search shows). It was only referenced in READMEs.

I guess based on the READMEs I don't totally grasp the significance of these experiments. As far as I can tell, they were the ones corresponding to the original S4 paper so it would seem like it could be a shame not to be able to reproduce it anymore. 
But maybe I misunderstand the READMEs and there are ways to do so with the "new" configs.

(Note: I had started looking into the old configurations because I couldn't get the new s4-sc config to run, but that's a different issue than the one here, so maybe I'll open another one for it if I can still not figure it out)

Thanks for the help!

**Comment by albertfgu** [comment]
The SC experiments should have later configs that produce results as good or better than the originals, in the same training setting and using the most recent code. So it is probably better to use those.

If you're having trouble getting the s4-sc config to run, then that is indeed an issue. Please file a separate GH issue!

**Comment by francoisgermain** [comment]
Sounds good, thanks for the clarification. I thought the best way forward was to make a pull request to remove the mentions to that folder, since it doesn't exist anyway. That should avoid any future confusion.
