### ISSUE TITLE
"pretrained_model" is not defined before being called in train.py

### ISSUE THREAD

**Issue by francoisgermain** [state-spaces/s4#132]
I am not using this section of the code at the moment so I don't have a full grasp of the goal of that section, but neither my IDE nor I can find where `pretrained_model` would be defined before this call:
https://github.com/state-spaces/s4/blob/a246043077dbff8563a6b172426443dced9a9d96/train.py#L714
My best guess at the moment is that the following line should say `pretrained_model` rather than `model`:
https://github.com/state-spaces/s4/blob/a246043077dbff8563a6b172426443dced9a9d96/train.py#L704
(`model` is already defined a few lines before so this line actually overwrites it)

Makes sense?

**Comment by albertfgu** [comment]
It looks like a legacy codepath. Feel free to remove it.

**Comment by francoisgermain** [comment]
I see. Well, considering someone might want to consider pretrained model, it could be a helpful starting point for whoever that is even if it's not functional as it is. That code won't be run without the associated hydra attributes anyway.

Thanks for clarifying. Closing.
