### ISSUE TITLE
AttributeError: 'SSMKernelDPLR' object has no attribute 'kernel'

### ISSUE THREAD

**Issue by IsabelFunke** [state-spaces/s4#136]
This seems to be a typo in the standalone S4 implementation (`models/s4/s4.py`) in class `SSMKernelDPLR`, at [Line 1378](
https://github.com/state-spaces/s4/blob/35cc2425115700c1b808008779c59148f764a17c/models/s4/s4.py#L1378C1-L1380C63). 

Code runs when `self.kernel` is renamed to `self.backend` (so that it is consistent with `SSMKernelDiag`)

**Comment by albertfgu** [comment]
Fixed in https://github.com/state-spaces/s4/commit/e757cef57d89e448c413de7325ed5601aceaac13
